// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqFE51UcOBh-d6PyAZHVKXHMFJPPgpQw',
    appId: '1:913274356409:android:2c2cfdeb7af8f90bc69168',
    messagingSenderId: '913274356409',
    projectId: 'latestom-462b9',
    storageBucket: 'latestom-462b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB41HDR3puF-TuINo9hALUFiMa-uzWBkms',
    appId: '1:913274356409:ios:a9c70865dcb2eeeac69168',
    messagingSenderId: '913274356409',
    projectId: 'latestom-462b9',
    storageBucket: 'latestom-462b9.appspot.com',
    androidClientId: '913274356409-i27pjgnndflq6l8ijpe10jirsevvu7f9.apps.googleusercontent.com',
    iosClientId: '913274356409-flkdsis884g3ut7l7lqgf2ea87ml2vmm.apps.googleusercontent.com',
    iosBundleId: 'com.omshribhakti.omshribhakti',
  );
}
